# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox,QWidget
import resources_rc
import luncher
import correctDic
import autoUpdate

class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 425)
        MainWindow.setMinimumSize(QtCore.QSize(643, 425))
        MainWindow.setMaximumSize(QtCore.QSize(643, 425))
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Zhenyu Zhang/Desktop/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(4.0)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Lunch = QtWidgets.QPushButton(self.centralwidget)
        self.Lunch.setGeometry(QtCore.QRect(440, 300, 151, 61))
        self.Lunch.setStyleSheet("font: 11pt \"YaHei Consolas Hybrid\";")
        self.Lunch.setObjectName("Lunch")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 191, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.settingsLable = QtWidgets.QLabel(self.formLayoutWidget)
        self.settingsLable.setObjectName("settingsLable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settingsLable)
        self.settingsComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.settingsComboBox.setObjectName("settingsComboBox")
        self.settingsComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settingsComboBox)
        self.versions = QtWidgets.QLabel(self.formLayoutWidget)
        self.versions.setObjectName("versions")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.versions)
        self.versionsComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.versionsComboBox.setObjectName("versionsComboBox")
        self.versionsComboBox.addItems(correctDic.getVersion(r".minecraft\versions"))#显示所有版本
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.versionsComboBox)
        self.sign_in = QtWidgets.QLabel(self.formLayoutWidget)
        self.sign_in.setObjectName("sign_in")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sign_in)
        self.sign_inComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.sign_inComboBox.setStyleSheet("")
        self.sign_inComboBox.setObjectName("sign_inComboBox")
        self.sign_inComboBox.addItem("")
        self.sign_inComboBox.addItem("")
        self.sign_inComboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sign_inComboBox)
        self.nickName = QtWidgets.QLabel(self.formLayoutWidget)
        self.nickName.setObjectName("nickName")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.nickName)
        self.nickNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nickNameLineEdit.setObjectName("nickNameLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nickNameLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 643, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menuPython_Minecraft_Luncher_0_0_1_Beta = QtWidgets.QMenu(self.menuBar)
        self.menuPython_Minecraft_Luncher_0_0_1_Beta.setObjectName("menuPython_Minecraft_Luncher_0_0_1_Beta")
        MainWindow.setMenuBar(self.menuBar)
        self.menu_3.addSeparator()
        self.menuPython_Minecraft_Luncher_0_0_1_Beta.addSeparator()
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menuPython_Minecraft_Luncher_0_0_1_Beta.menuAction())

        self.retranslateUi(MainWindow)
        self.Lunch.clicked.connect(self.addNum)#调用函数，一定要设置成self.addNum，不然不行
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.settingsComboBox, self.versionsComboBox)
        MainWindow.setTabOrder(self.versionsComboBox, self.sign_inComboBox)
        MainWindow.setTabOrder(self.sign_inComboBox, self.nickNameLineEdit)
        MainWindow.setTabOrder(self.nickNameLineEdit, self.Lunch)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PMCL"))
        self.Lunch.setText(_translate("MainWindow", "启动 Minecraft"))
        self.settingsLable.setText(_translate("MainWindow", "配置"))
        self.settingsComboBox.setItemText(0, _translate("MainWindow", "未启用"))
        self.versions.setText(_translate("MainWindow", "版本"))
        self.sign_in.setText(_translate("MainWindow", "登录"))
        self.sign_inComboBox.setItemText(0, _translate("MainWindow", "正版登录"))
        self.sign_inComboBox.setItemText(1, _translate("MainWindow", "离线登录"))
        self.sign_inComboBox.setItemText(2, _translate("MainWindow", "外置登录"))
        self.nickName.setText(_translate("MainWindow", "昵称"))
        self.menu.setTitle(_translate("MainWindow", "主页"))
        self.menu_2.setTitle(_translate("MainWindow", "游戏设置"))
        self.menu_3.setTitle(_translate("MainWindow", "启动器设置"))
        self.menuPython_Minecraft_Luncher_0_0_1_Beta.setTitle(_translate("MainWindow", "Python Minecraft Luncher 0.0.1-Beta"))

    def addNum(self):
        if self.nickNameLineEdit.text() == "":
            reply = QMessageBox.warning(self,'警告',"请填写你的昵称") 
        else:         
            nick_name = self.nickNameLineEdit.text()
            sign_in_method = self.sign_inComboBox.currentText()
            version = self.versionsComboBox.currentText()
            autoUpdate.lunchCount("http://127.0.0.1:5000/count")
            luncher.forgeLuncher('java','./.minecraft',version,nick_name,"480","854")
            
import resources_rc
