# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget
from PyQt5.QtCore import *

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        self.setupUi(self)
        self.center()
        self.retranslateUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 657)
        self.setWindowFlags(Qt.FramelessWindowHint)  # 去边框
        self.setAttribute(Qt.WA_TranslucentBackground)  # 设置窗口背景透明
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(320, 100, 181, 41))
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 100, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/img/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(380, 200, 101, 31))
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.userName = QtWidgets.QLabel(self.centralwidget)
        self.userName.setGeometry(QtCore.QRect(380, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(14)
        self.userName.setFont(font)
        self.userName.setObjectName("userName")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(260, 170, 251, 171))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/img/background.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(510, 160, 261, 361))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/img/background.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(190, 40, 781, 561))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/img/background.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.userImg = QtWidgets.QLabel(self.centralwidget)
        self.userImg.setGeometry(QtCore.QRect(280, 190, 81, 81))
        self.userImg.setText("")
        self.userImg.setPixmap(QtGui.QPixmap(":/img/hahaha.jpg"))
        self.userImg.setScaledContents(True)
        self.userImg.setObjectName("userImg")
        self.changeUser = QtWidgets.QPushButton(self.centralwidget)
        self.changeUser.setGeometry(QtCore.QRect(330, 280, 75, 23))
        self.changeUser.setObjectName("changeUser")
        self.changeUser.setStyleSheet("""
        QPushButton{
    color:White;
    border-radius: 7px;
    font-family:微软雅黑;
    background:#6633FF;
    border:1px;
}
QPushButton:hover{
    background:#6666FF;
}
QPushButton:pressed{
    background:#6600FF;
}
        """)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(260, 340, 251, 171))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/img/background.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(280, 410, 204, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ModManage = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(12)
        self.ModManage.setFont(font)
        self.ModManage.setObjectName("ModManage")
        self.ModManage.setStyleSheet("""
        QPushButton{
    color:White;
    border-radius: 7px;
    font-family:微软雅黑;
    background:#6633FF;
    border:1px;
}
QPushButton:hover{
    background:#6666FF;
}
QPushButton:pressed{
    background:#6600FF;
}""")
        self.gridLayout.addWidget(self.ModManage, 0, 0, 1, 1)
        self.setting = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.setting.setStyleSheet("""
        QPushButton{
    color:White;
    border-radius: 7px;
    font-family:微软雅黑;
    background:#6633FF;
    border:1px;
}
QPushButton:hover{
    background:#6666FF;
}
QPushButton:pressed{
    background:#6600FF;
}
""")
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(12)
        self.setting.setFont(font)
        self.setting.setObjectName("setting")
        self.gridLayout.addWidget(self.setting, 1, 0, 1, 1)
        self.gameSetting = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(12)
        self.gameSetting.setFont(font)
        self.gameSetting.setObjectName("gameSetting")
        self.gameSetting.setStyleSheet("""
        QPushButton{
    color:White;
    border-radius: 7px;
    font-family:微软雅黑;
    background:#6633FF;
    border:1px;
}
QPushButton:hover{
    background:#6666FF;
}
QPushButton:pressed{
    background:#6600FF;
}""")
        self.gridLayout.addWidget(self.gameSetting, 0, 1, 1, 1)
        self.update = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(12)
        self.update.setFont(font)
        self.update.setObjectName("update")
        self.update.setStyleSheet("""
        QPushButton{
    color:White;
    border-radius: 7px;
    font-family:微软雅黑;
    background:#6633FF;
    border:1px;
}
QPushButton:hover{
    background:#6666FF;
}
QPushButton:pressed{
    background:#6600FF;
}
""")
        self.gridLayout.addWidget(self.update, 1, 1, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(290, 370, 181, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.versionComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.versionComboBox.setObjectName("versionComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.versionComboBox)
        self.lunch = QtWidgets.QPushButton(self.centralwidget)
        self.lunch.setGeometry(QtCore.QRect(770, 440, 141, 51))
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        font.setPointSize(12)
        self.lunch.setFont(font)
        self.lunch.setObjectName("lunch")
        self.lunch.setStyleSheet("""
        QPushButton{
    color:White;
    border-radius: 7px;
    font-family:微软雅黑;
    background:#6633FF;
    border:1px;
}
QPushButton:hover{
    background:#6666FF;
}
QPushButton:pressed{
    background:#6600FF;
}""")
        self.bbs = QtWidgets.QLabel(self.centralwidget)
        self.bbs.setGeometry(QtCore.QRect(620, 240, 54, 12))
        self.bbs.setObjectName("bbs")
        self.small = QtWidgets.QPushButton(self.centralwidget)
        self.small.setGeometry(QtCore.QRect(830, 100, 21, 21))
        self.small.setObjectName("small")
        self.small.setStyleSheet("""
        QPushButton{
    background:#6C6C6C;
    color:white;
font-size:16px;border-radius: 8px;font-family: 微软雅黑;
}
QPushButton:hover{                    
    background:#9D9D9D;
}
QPushButton:pressed{
    border: 1px solid #3C3C3C!important;
}""")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 100, 21, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("""
        QPushButton{
    background:#CE0000;
    color:white;
font-size:16px;border-radius: 8px;font-family: 微软雅黑;
}
QPushButton:hover{                    
    background:#FF2D2D;
}
QPushButton:pressed{
    border: 1px solid #3C3C3C!important;
    background:#AE0000;
}""")
        self.pushButton_2.clicked.connect(self.close)
        self.label_21.raise_()
        self.label_23.raise_()
        self.label_16.raise_()
        self.title.raise_()
        self.label_3.raise_()
        self.label_10.raise_()
        self.label_20.raise_()
        self.userImg.raise_()
        self.userName.raise_()
        self.changeUser.raise_()
        self.gridLayoutWidget.raise_()
        self.formLayoutWidget.raise_()
        self.lunch.raise_()
        self.bbs.raise_()
        self.small.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "PMCL 0.0.1-BETA"))
        self.label_10.setText(_translate("MainWindow", "Welcome,"))
        self.userName.setText(_translate("MainWindow", "xiao_zhe"))
        self.changeUser.setText(_translate("MainWindow", "切换用户"))
        self.ModManage.setText(_translate("MainWindow", "Mod管理"))
        self.setting.setText(_translate("MainWindow", "启动器设置"))
        self.gameSetting.setText(_translate("MainWindow", "游戏设置"))
        self.update.setText(_translate("MainWindow", "检查更新"))
        self.label_11.setText(_translate("MainWindow", "版本"))
        self.lunch.setText(_translate("MainWindow", "启动 Minecraft"))
        self.bbs.setText(_translate("MainWindow", "公告"))
        self.small.setText(_translate("MainWindow", ""))
        self.pushButton_2.setText(_translate("MainWindow", ""))
    @pyqtSlot()
    def on_small_clicked(self):
        # 最小化
        self.showMinimized()
    def center(self):
        qr  =  self.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())
import resources_rc
